config/routes.rb
Rails.application.routes.draw do
  resources :shifts
  resources :organisations
  get 'home/index'
  root 'home#index'
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "edit", to: "users#edit"

  delete "logout", to: "sessions#destroy"
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :users 
  has_many :shifts 

  validates :name, :presence => true 
  validates :hourly_rate, :presence => true 
  attr_accessor :organisation 

end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :user

  validates :full_name, :presence => true 
  validates :shift_date, :presence => true 
  validates :start_time, :presence => true
  validates :finish_time, :presence => true 

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :organisation
  has_many :shifts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :current_organisation, :delete_organisation
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_organisation
    @current_organisation = Organisation.first
  end

  # def hours_worked
  #   (((@shift.finish_time.hour.minute + @shift.finish_time.min).to_f - (@shift.start_time.hour.minute + @shift.start_time.min) - @shift.break_length.to_i) / 60).to_f.round(2)
  # end
  
  def logged_in?
    !!current_user
  end

  def delete_organisation
    @shift = Shift.all
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: %i[ show edit update destroy ]

  # GET /organisations or /organisations.json
  def index
    @organisations = Organisation.all
  end

  # GET /organisations/1 or /organisations/1.json
  def show
  end

  # GET /organisations/new
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
  end

  # POST /organisations or /organisations.json
  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to organisation_url(@organisation), notice: "Organisation was successfully created." }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisations/1 or /organisations/1.json
  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to organisation_url(@organisation), notice: "Organisation was successfully updated." }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1 or /organisations/1.json
  def destroy
    @organisation.destroy

    respond_to do |format|
      format.html { redirect_to organisations_url, notice: "Organisation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organisation_params
      params.require(:organisation).permit(:name, :hourly_rate)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to organisations_path
    else
      flash.now[:alert] = "There was something wrong with your login details."
      render 'new'
    end
  end
   
  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to root_path
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]
  attr_accessor :shifts
  # GET /shifts or /shifts.json
  def filter
    shift = Shift.find(params['name']['id']) 
    @shifts = shift.name
  end  
    
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1 or /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    # @shift = Shift.new
    @shift = current_user.shifts.build
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts or /shifts.json
  def create
    # @shift = Shift.new(shift_params)
    @shift = current_user.shifts.build(shift_params)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to shift_url(@shift), notice: "Shift was successfully created." }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1 or /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to shift_url(@shift), notice: "Shift was successfully updated." }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1 or /shifts/1.json
  def destroy
    @shift.destroy

    respond_to do |format|
      format.html { redirect_to shifts_url, notice: "Shift was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @shift = current_user.shifts.find_by(id: params[:id])
    redirect_to shifts_path, notice: "Not authourised to edit this shift" if @shift.nil?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shift_params
      params.require(:shift).permit(:full_name, :shift_date, :start_time, :finish_time, :break_length, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User created."
      redirect_to login_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      flash[:notice] = "User updated."
      redirect_to organisations_path
    else
      render 'edit'
    end
  end
 private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :organisation_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <%= link_to 'Adnat', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'Organisations', organisations_path, class:"navbar-brand"%>
          </li>
          
          <li class="nav-item">
            <%=link_to "Edit Profile", edit_user_path(current_user.id), class:"navbar-brand"%>
          </li>

          <li class="nav-item">
            <%=button_to "Log Out", logout_path, method: :delete%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Adnat</h1>
<% if logged_in? %>
  <h3>Logged in as <%=current_user.name%></h3>
<% end %>
<% if !logged_in? %>
  <%=button_to "Sign Up", signup_path, :method => :get, class:"btn btn-outline-secondary"%>
  <%=button_to "Log In", login_path, :method => :get, class:"btn btn-outline-secondary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Adnat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/organisations/_form.html.erb
<%= form_with(model: organisation) do |form| %>
  <% if organisation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
        <% organisation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :hourly_rate, style: "display: block" %>
    <%= form.number_field :hourly_rate %>
  </div>

  <div class="field form-group">
    <%=form.number_field :user_id, id: :user_organisation_id, class:"form-control", value: current_user.id, type: :hidden%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/organisations/_organisation.html.erb
<div id="<%= dom_id organisation %>">
  <p>
    <strong>Name:</strong>
    <%= organisation.name %>
  </p>

  <p>
    <strong>Hourly rate:</strong>
    <%= organisation.hourly_rate %>
  </p>

</div>

app/views/organisations/edit.html.erb
<h1>Editing organisation</h1>

<%= render "form", organisation: @organisation %>

<br>

<div>
  <%= link_to "Show this organisation", @organisation %> |
  <%= link_to "Back to organisations", organisations_path %>
</div>

app/views/organisations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Adnat</h1>
<% if logged_in? %>
  <h3>Logged in as <%=current_user.name%></h3>
  Join an existing organisation or create a new one
<% end %>

<h1>Organisations</h1>

<table class="table table-hover">
  <thead class='thead-dark'>
    <tr>
      <th>Name</th>
      <th>Hourly Rate</th>

      <th> </th>
    </tr>
  </thead>


  <tbody>
    <% @organisations.each do |organisation| %>
      <tr>
          <td><%= organisation.name %></td>
          <td><%= organisation.hourly_rate %> </td>

          <td><%= link_to "Join", organisation%></td>
          <td><%= link_to "Edit", edit_organisation_path(organisation) %></td>
 
          <td><%= link_to 'Delete', organisation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
<% if @organisations.count < 1%>
  <%= link_to "New organisation", new_organisation_path %>
<% end %>
</tbody>
</table>

app/views/organisations/new.html.erb
<h1>New organisation</h1>

<%= render "form", organisation: @organisation %>

<br>

<div>
  <%= link_to "Back to organisations", organisations_path %>
</div>

app/views/organisations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @organisation %>

<div>
  <%= link_to "Back to organisations", organisations_path %> |
  <%= link_to "Edit this organisation", edit_organisation_path(@organisation) %> |
  <%= link_to "View Shifts", shifts_path %>


 <%= form_with(model: @organisation, local: true) do |form| %>
  <div class="field form-group">
    <%=form.number_field :user_id, id: :user_organisation_id, class:"form-control", value: @organisation.id, type: :hidden%>
  </div>
<% end %>
  <%= button_to "Destroy this organisation", @organisation, method: :delete %>
</div>

app/views/shifts/_form.html.erb
<%= form_with(model: shift) do |form| %>
  <% if shift.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
        <% shift.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :full_name, style: "display: block" %>
    <%= form.text_field :full_name %>
  </div>
  
  <div>
    <%= form.label :shift_date, style: "display: block" %>
    <%= form.date_field :shift_date %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.time_field :start_time %>
  </div>

  <div>
    <%= form.label :finish_time, style: "display: block" %>
    <%= form.time_field :finish_time %>
  </div>

  <div>
    <%= form.label :break_length, style: "display: block" %>
    <%= form.number_field :break_length %>
  </div>

  <div>
    <%= form.submit %>
  </div>

  <div class="field form-group">
    <%=form.number_field :user_id, id: :users_user_id, class:"form-control", value: current_user.id, type: :hidden%>
  </div>
<% end %>

app/views/shifts/_shift.html.erb
<div id="<%= dom_id shift %>">
  <p>
    <strong>Full name:</strong>
    <%= shift.full_name %>
  </p>

  <p>
    <strong>Shift date:</strong>
    <%= "#{shift.shift_date.mday}/#{shift.shift_date.mon}/#{shift.shift_date.year}" %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= "#{shift.start_time.hour}:#{shift.start_time.min}" %>
  </p>

  <p>
    <strong>Finish time:</strong>
    <%= "#{shift.finish_time.hour}:#{shift.finish_time.min}" %>
  </p>

  <p>
    <strong>Break length:</strong>
    <%= shift.break_length %>
  </p>

</div>

app/views/shifts/edit.html.erb
<h1>Editing shift</h1>

<%= render "form", shift: @shift %>

<br>

<div>
  <%= link_to "Show this shift", @shift %> |
  <%= link_to "Back to shifts", shifts_path %>
</div>

app/views/shifts/index.html.erb
<p style="color: green"><%= notice %></p>
<%=@organisations%>
<h1>Shifts</h1>
<table class="table table-hover">
  <thead class='thead-dark'>
    <tr>
      <th>Employee Name</th>
      <th>Shift Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Break Length (minutes)</th>
      <th>Hours Worked</th>
      <th>Shift Cost</th>
      <th> </th>
    </tr>
  </thead>
<div id="shifts">
  <tbody>
  
  <% @shifts.each do |shift| %>
    <% if shift.user == current_user %>
    <tr>
      <td><%= shift.full_name %></td>
      <td><%= "#{shift.shift_date.mday}/#{shift.shift_date.mon}/#{shift.shift_date.year}"%></td>
      <td><%= "#{shift.start_time.strftime('%H')}:#{shift.start_time.strftime('%M')}" %></td> 
      <td><%= "#{shift.finish_time.strftime('%H')}:#{shift.finish_time.strftime('%M')}" %> </td>
      <td><%= shift.break_length %> </td>
      <td><%= (((shift.finish_time.hour.minute + shift.finish_time.min).to_f - (shift.start_time.hour.minute + shift.start_time.min) - shift.break_length.to_i) / 60).to_f.round(2) %> </td>
      <td><%= (current_organisation.hourly_rate * (((shift.finish_time.hour.minute + shift.finish_time.min).to_f - (shift.start_time.hour.minute + shift.start_time.min) - shift.break_length.to_i) / 60).to_f.round(2)).round(2)%> </td>
      <td><%= link_to "Show", shift %></td>
      <td><%= link_to "Edit", edit_shift_path(shift) %></td>
      <td><%= link_to 'Delete', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  <% end %>
</div>

<%= link_to "New shift", new_shift_path %>

</tbody>
</table>

app/views/shifts/new.html.erb
<h1>New shift</h1>

<%= render "form", shift: @shift %>

<br>

<div>
  <%= link_to "Back to shifts", shifts_path %>
</div>

app/views/shifts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shift %>

<div>
  <%= link_to "Edit this shift", edit_shift_path(@shift) %> |
  <%= link_to "Back to shifts", shifts_path %>

  <%= button_to "Destroy this shift", @shift, method: :delete %>
</div>

app/views/users/edit.html.erb
<h2>Edit <%=current_user.name%>'s Profile </h2>

<%= form_with(model: @user, local: true) do |f| %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "current-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>

  <div class="field form-group">
  <%=f.number_field :user_id, id: :users_user_id, class:"form-control", value: current_user.id, type: :hidden%>
</div>
<% end %>

<h3>Cancel my account</h3>

<%= link_to "Back", :back %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with(model: @user, local: true) do |f| %>
 
  <div class="form-group">
    <%= f.label :name %><br/>
    <%= f.text_field :name, class: "form-control" %>
  </div>
   
  <div class="form-group">
    <%= f.label :email %><br/>
    <%= f.email_field :email, class: "form-control" %>
  </div>
   
  <div class="form-group">
    <%= f.label :password %><br/>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  
  <div class="field form-group">   
    <%= f.number_field :organisation_id, class:"form-control", value: 0, type: :hidden %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>
   
  <% end %>